/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface CardMatches {
  announced_participants_json: Generated<string>;
  bonus_questions_json: Generated<string>;
  card_id: string;
  created_at: Generated<string>;
  description: Generated<string>;
  id: string | null;
  is_custom: Generated<number>;
  match_type: string;
  participants_json: Generated<string>;
  points: number | null;
  sort_order: number;
  surprise_slots: number | null;
  title: string;
  updated_at: Generated<string>;
}

export interface CardMatchOverrides {
  announced_participants_json: string | null;
  bonus_questions_json: string | null;
  card_id: string;
  description: string | null;
  hidden: Generated<number>;
  id: string | null;
  participants_json: string | null;
  points: number | null;
  sort_order: number | null;
  surprise_slots: number | null;
  template_match_id: string;
  title: string | null;
  updated_at: Generated<string>;
}

export interface CardOverrides {
  card_id: string | null;
  default_points: number | null;
  event_date: string | null;
  event_name: string | null;
  event_tagline: string | null;
  name: string | null;
  tiebreaker_label: string | null;
  updated_at: Generated<string>;
}

export interface Cards {
  created_at: Generated<string>;
  default_points: number | null;
  event_date: string | null;
  event_name: string | null;
  event_tagline: string | null;
  id: string | null;
  is_template: Generated<number>;
  name: string | null;
  owner_id: string | null;
  public: Generated<number>;
  template_card_id: string | null;
  tiebreaker_label: string | null;
  updated_at: Generated<string>;
}

export interface Sheets {
  created_at: Generated<string>;
  id: string | null;
  owner_id: string;
  payload_json: string;
  public: Generated<number>;
  title: string;
  updated_at: Generated<string>;
}

export interface DB {
  card_match_overrides: CardMatchOverrides;
  card_matches: CardMatches;
  card_overrides: CardOverrides;
  cards: Cards;
  sheets: Sheets;
}
